#!/usr/bin/env ruby
# frozen_string_literal: true

require "xattr"
require "optparse"

def quit(msg, exit_value = 1)
  puts msg
  exit(exit_value)
end

op = OptionParser.new do |opts|
  opts.banner = "Usage:  #{File.basename($PROGRAM_NAME)} FILE [[-]ATTRIBUTE [VALUE]]

    * FILE                 -> The attributes of FILE.
    * FILE ATTRIBUTE       -> The value of FILE's ATTRIBUTE
    * FILE -ATTRIBUTE      -> Deletes FILE's ATTRIBUTE
    * FILE ATTRIBUTE VALUE -> Sets FILE's ATTRIBUTE to VALUE"

  opts.separator("")

  opts.on("-h", "--help", "Show this message.") do
    quit(opts, 0)
  end
end

begin
  op.parse(ARGV[0, 1])

  argv_len = ARGV.length
  if argv_len.positive?
    xattr = Xattr.new(ARGV[0])
    result = case argv_len
             when 2
               if ARGV[1][/^-/]
                 xattr.remove(ARGV[1].sub("-", ""))
               else
                 xattr.get(ARGV[1])
               end
             when 3
               xattr.set(ARGV[1], ARGV[2])
             else
               xattr.list.join("\n")
             end
    puts result if result&.any?
  else
    quit(opts)
  end
rescue SystemCallError => e
  quit("#{e.class}: #{e}")
rescue StandardError => e
  quit("#{e.class}: #{e}\n\n#{op}")
end
